import Head from "next/head";
import { useRef, useEffect, useState } from "react";
import styled from "styled-components";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";

const Container = styled.div`
  cursor: grab;
`;

export default function Home() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(
      25, // 相機的垂直視野
      1440 / window.innerHeight, // 相機的外觀比例
      0.1, // 接近的相機視體平面距離值
      1000 //遠的相機視體平面距離值
    );
    camera.position.x = 0;
    camera.position.y = 0;
    camera.position.z = 50;

    const renderer = new THREE.WebGLRenderer();
    renderer.setSize(1440, window.innerHeight);

    const dracoLoader = new DRACOLoader();
    dracoLoader.setDecoderPath("draco/");
    dracoLoader.setDecoderConfig({ type: "js" });

    containerRef.current?.appendChild(renderer.domElement);

    // Add a light source
    const light = new THREE.PointLight(0xffffff);
    light.position.set(50, 50, 50);
    scene.add(light);

    // Load the .glb file using the GLTFLoader
    const loader = new GLTFLoader();
    loader.setDRACOLoader(dracoLoader);
    loader.load("island.glb", (gltf) => {
      scene.add(gltf.scene);
      renderer.render(scene, camera);
    });

    containerRef.current?.addEventListener("mousedown", (event) => {
      let lastX = event.clientX;
      let lastY = event.clientY;
      const onMouseMove = (e: MouseEvent) => {
        const deltaX = e.clientX - lastX;
        const deltaY = e.clientY - lastY;
        camera.position.x += deltaX * 0.01;
        camera.position.y -= deltaY * 0.01;
        lastX = e.clientX;
        lastY = e.clientY;
        renderer.render(scene, camera);
      };
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", () => {
        document.removeEventListener("mousemove", onMouseMove);
      });
    });
  }, []);

  return (
    <>
      <Head>
        <title>Riv Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container ref={containerRef} />
      </main>
    </>
  );
}
